In [1]:
import numpy as np

def normalize(v):
    """Normalize a vector."""
    norm = np.linalg.norm(v)
    if norm == 0: 
       return v
    return v / norm

# Define the initial vector A and target vector B
A = np.array([-8.02, -0.62, 6.4])
B = np.array([0, 0, 9.8])

# Normalize the vectors
A_norm = normalize(A)
B_norm = normalize(B)

# Calculate the cross product to find the rotation axis
u = np.cross(A_norm, B_norm)

# Normalize the rotation axis
u = normalize(u)

# Calculate the dot product to find the rotation angle
theta = np.arccos(np.dot(A_norm, B_norm))

# Components of the rotation axis
ux, uy, uz = u

# Calculate the rotation matrix using the axis-angle formula
cos_theta = np.cos(theta)
sin_theta = np.sin(theta)
one_minus_cos_theta = 1 - cos_theta

R = np.array([
    [cos_theta + ux**2 * one_minus_cos_theta, ux * uy * one_minus_cos_theta - uz * sin_theta, ux * uz * one_minus_cos_theta + uy * sin_theta],
    [uy * ux * one_minus_cos_theta + uz * sin_theta, cos_theta + uy**2 * one_minus_cos_theta, uy * uz * one_minus_cos_theta - ux * sin_theta],
    [uz * ux * one_minus_cos_theta - uy * sin_theta, uz * uy * one_minus_cos_theta + ux * sin_theta, cos_theta + uz**2 * one_minus_cos_theta]
])

# Apply the rotation matrix to the initial vector A
A_rotated = np.dot(R, A_norm)

# Scale the rotated vector to match the magnitude of the target vector B
A_rotated = A_rotated * np.linalg.norm(B)

# Display the results
print('Initial vector A:')
print(A)
print('Normalized initial vector A:')
print(A_norm)
print('Target vector B:')
print(B)
print('Normalized target vector B:')
print(B_norm)
print('Rotation axis (normalized):')
print(u)
print('Rotation angle (degrees):')
print(np.degrees(theta))
print('Rotation matrix R:')
print(R)
print('Rotated vector A:')
print(A_rotated)


Initial vector A:
[-8.02 -0.62  6.4 ]
Normalized initial vector A:
[-0.78020585 -0.06031517  0.62260816]
Target vector B:
[0.  0.  9.8]
Normalized target vector B:
[0. 0. 1.]
Rotation axis (normalized):
[-0.07707676  0.99702516  0.        ]
Rotation angle (degrees):
51.49315291598431
Rotation matrix R:
[[ 0.62485018 -0.02900161  0.78020585]
 [-0.02900161  0.99775798  0.06031517]
 [-0.78020585 -0.06031517  0.62260816]]
Rotated vector A:
[-1.32177255e-15 -2.04003481e-16  9.80000000e+00]


In [20]:
R_new = (9.8/10.279)*R


print(np.linalg.norm(A))

np.dot(R_new,A)

10.279338500117602


array([-1.06858966e-15, -1.11022302e-16,  9.80032273e+00])

In [21]:
#create a function to return the rotation matrix for a given vector

def create_rotation_matrix(v):
    B = np.array([0, 0, 9.8])

    #store the norm of v
    v_normz = np.linalg.norm(v)

    # Normalize the vectors
    v_norm = normalize(v)
    B_norm = normalize(B)

    # Calculate the cross product to find the rotation axis
    u = np.cross(v_norm, B_norm)

    # Normalize the rotation axis
    u = normalize(u)

    # Calculate the dot product to find the rotation angle
    theta = np.arccos(np.dot(v_norm, B_norm))

    # Components of the rotation axis
    ux, uy, uz = u

    # Calculate the rotation matrix using the axis-angle formula
    cos_theta = np.cos(theta)
    sin_theta = np.sin(theta)
    one_minus_cos_theta = 1 - cos_theta

    R = np.array([
        [cos_theta + ux**2 * one_minus_cos_theta, ux * uy * one_minus_cos_theta - uz * sin_theta, ux * uz * one_minus_cos_theta + uy * sin_theta],
        [uy * ux * one_minus_cos_theta + uz * sin_theta, cos_theta + uy**2 * one_minus_cos_theta, uy * uz * one_minus_cos_theta - ux * sin_theta],
        [uz * ux * one_minus_cos_theta - uy * sin_theta, uz * uy * one_minus_cos_theta + ux * sin_theta, cos_theta + uz**2 * one_minus_cos_theta]
    ])

    R = (9.8/(v_normz))*R

    return R

In [22]:
np.dot(create_rotation_matrix(A),A)

array([-1.40859546e-15, -2.22044605e-16,  9.80000000e+00])

In [26]:
v_new = np.array([-7.83,1.61,5.93])
print(create_rotation_matrix(v_new))

[[ 0.6027638   0.07851487  0.77457531]
 [ 0.07851487  0.96846523 -0.15926772]
 [-0.77457531  0.15926772  0.58661961]]
